version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Kuala_Lumpur'

updates:
  - package-ecosystem: 'uv'
    directory: '/'
    multi-ecosystem-group: 'python'
    patterns:
      - '*'

  - package-ecosystem: 'pip'
    directory: '/'
    multi-ecosystem-group: 'python'
    patterns:
      - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Kuala_Lumpur'
