"""
APRS Symbol Definitions
Source: symbolsX.txt (25 Nov 2015), symbols-new.txt (17 Mar 2021)
"""

APRS_SYMBOLS = {
    # Primary Symbol Table (/)
    "/!": "Police, Sheriff",
    "/\"": "reserved (was rain)",
    "/#": "DIGI (white center)",
    "/$": "PHONE",
    "/%": "DX CLUSTER",
    "/&": "HF GATEway",
    "/'": "Small AIRCRAFT (SSID-11)",
    "/(": "Mobile Satellite Station",
    "/)": "Wheelchair (handicapped)",
    "/*": "SnowMobile",
    "/+": "Red Cross",
    "/,": "Boy Scouts",
    "/-": "House QTH (VHF)",
    "/.": "X",
    "//": "Red Dot",
    "/0": "# circle (obsolete)",
    "/1": "TBD (these were numbered)",
    "/2": "TBD (circles like pool)",
    "/3": "TBD (balls. But with)",
    "/4": "TBD (overlays, we can)",
    "/5": "TBD (put all #'s on one)",
    "/6": "TBD (So 1-9 are available)",
    "/7": "TBD (for new uses?)",
    "/8": "TBD (They are often used)",
    "/9": "TBD (as mobiles at events)",
    "/:": "FIRE",
    "/;": "Campground (Portable ops)",
    "/<": "Motorcycle (SSID-10)",
    "/=": "RAILROAD ENGINE",
    "/>": "CAR (SSID-9)",
    "/?": "SERVER for Files",
    "/@": "HC FUTURE predict (dot)",
    "/A": "Aid Station",
    "/B": "BBS or PBBS",
    "/C": "Canoe",
    "/D": "",
    "/E": "EYEBALL (Events, etc!)",
    "/F": "Farm Vehicle (tractor)",
    "/G": "Grid Square (6 digit)",
    "/H": "HOTEL (blue bed symbol)",
    "/I": "TcpIp on air network stn",
    "/J": "",
    "/K": "School",
    "/L": "PC user (Jan 03)",
    "/M": "MacAPRS",
    "/N": "NTS Station",
    "/O": "BALLOON (SSID-11)",
    "/P": "Police",
    "/Q": "TBD",
    "/R": "REC. VEHICLE (SSID-13)",
    "/S": "SHUTTLE",
    "/T": "SSTV",
    "/U": "BUS (SSID-2)",
    "/V": "ATV",
    "/W": "National WX Service Site",
    "/X": "HELO (SSID-6)",
    "/Y": "YACHT (sail) (SSID-5)",
    "/Z": "WinAPRS",
    "/[": "Human/Person (SSID-7)",
    "/\\": "TRIANGLE(DF station)",
    "/]": "MAIL/PostOffice(was PBBS)",
    "/^": "LARGE AIRCRAFT",
    "/_": "WEATHER Station (blue)",
    "/`": "Dish Antenna",
    "/a": "AMBULANCE (SSID-1)",
    "/b": "BIKE (SSID-4)",
    "/c": "Incident Command Post",
    "/d": "Fire dept",
    "/e": "HORSE (equestrian)",
    "/f": "FIRE TRUCK (SSID-3)",
    "/g": "Glider",
    "/h": "HOSPITAL",
    "/i": "IOTA (islands on the air)",
    "/j": "JEEP (SSID-12)",
    "/k": "TRUCK (SSID-14)",
    "/l": "Laptop (Jan 03) (Feb 07)",
    "/m": "Mic-E Repeater",
    "/n": "Node (black bulls-eye)",
    "/o": "EOC",
    "/p": "ROVER (puppy, or dog)",
    "/q": "GRID SQ shown above 128 m",
    "/r": "Repeater (Feb 07)",
    "/s": "SHIP (pwr boat) (SSID-8)",
    "/t": "TRUCK STOP",
    "/u": "TRUCK (18 wheeler)",
    "/v": "VAN (SSID-15)",
    "/w": "WATER station",
    "/x": "xAPRS (Unix)",
    "/y": "YAGI @ QTH",
    "/z": "TBD",
    "/{": "",
    "/|": "TNC Stream Switch",
    "/}": "",
    "/~": "TNC Stream Switch",

    # Secondary/Alternate Symbol Table (\)
    "\\!": "Emergency (E=ELT/EPIRB, V=Volcanic Eruption/Lava)",
    "\\\"": "reserved",
    "\\#": "Digipeater (1=WIDE1-1, A=Alt-In, E=Emergency, I=I-gate, L=trapping, P=PacComm, S=SSn-N, X=eXperimental, V=Viscous, W=WIDEn-N)",
    "\\$": "Bank or ATM (U=USD, L=GBP, Y=JPY)",
    "\\%": "Power Plant (C=Coal, E=Emergency, G=Gas, H=Hydro, N=Nuclear, P=Portable, R=Renewable, S=Solar, T=Thermal, W=Wind)",
    "\\&": "Gateway (I=Generic IGate, L=Lora, R=RX only, P=PSKmail, T=1-hop TX, W=WIRES-X, 2=2-hop TX)",
    "\\'": "Incident (A=Auto, H=Hazardous, M=Multi-Vehicle, P=Pileup, T=Truck wreck)",
    "\\(": "Cloudy (P=Partly, W=Wall, F=Funnel)",
    "\\)": "Firenet MEO, MODIS Earth Obs.",
    "\\*": "AVAIL (SNOW moved to ` overlayed S)",
    "\\+": "Church",
    "\\,": "Girl Scouts",
    "\\-": "House (5=50Hz, 6=60Hz, B=Battery, C=Combined, E=Emergency, G=Geothermal, H=Hydro, O=Operator, S=Solar, W=Wind)",
    "\\.": "Ambiguous (Big Question mark)",
    "\\/": "Waypoint Destination",
    "\\0": "Circle (A=Allstar, E=Echolink, I=IRLP, S=Staging Area, V=VOIP, W=WIRES)",
    "\\1": "AVAIL",
    "\\2": "AVAIL",
    "\\3": "AVAIL",
    "\\4": "AVAIL",
    "\\5": "AVAIL",
    "\\6": "AVAIL",
    "\\7": "AVAIL",
    "\\8": "Network Node (8=802.11, G=802.11G)",
    "\\9": "Gas Station (blue pump)",
    "\\:": "AVAIL (Hail ==> ` overlayed H)",
    "\\;": "Portable/Park/Picnic (F=Field Day, I=IOTA, S=SOTA, W=WOTA)",
    "\\<": "ADVISORY (one WX flag)",
    "\\=": "Rail (B=Bus-rail, C=Commuter, D=Diesel, E=Electric, F=Freight, G=Gondola, H=High Speed, I=Inclined, L=Elevated, M=Monorail, P=Passenger, S=Steam, T=Terminal, U=Subway, X=eXcursion)",
    "\\>": "Car/Vehicle (1-9=numbered, 3=Model 3, B=BEV, D=DIY, E=Ethanol, F=Fuelcell, H=Hybrid, L=Leaf, P=PHEV, S=Solar, T=Tesla, V=Volt, X=Model X)",
    "\\?": "INFO Kiosk (Blue box with ?)",
    "\\@": "HURICANE/Trop-Storm",
    "\\A": "Box (DTMF/RFID/etc) (9=Mobile DTMF, 7=HT DTMF, H=House DTMF, E=Echolink DTMF, I=IRLP DTMF, R=RFID, A=AllStar DTMF, D=D-Star, X=OLPC)",
    "\\B": "AVAIL (Blowing Snow ==> E overlayed B",
    "\\C": "Coast Guard",
    "\\D": "Depot (A=Airport, F=Ferry, H=Heloport, R=Rail, B=Bus, L=Light Rail/Subway, S=Seaport)",
    "\\E": "Visibility (H=Haze, S=Smoke, B=Blowing Snow, D=Blowing Dust/Sand, F=Fog)",
    "\\F": "AVAIL (FrzngRain ==> `F)",
    "\\G": "AVAIL (Snow Shwr ==> I overlayed S)",
    "\\H": "Haze/Hazard (M=Methane, R=Radiation, W=Hazardous Waste, X=Skull&Crossbones)",
    "\\I": "Shower (R=Rain, S=Snow, L=Lightening)",
    "\\J": "AVAIL (Lightening ==> I overlayed L)",
    "\\K": "Kenwood HT (W)",
    "\\L": "Lighthouse",
    "\\M": "MARS (A=Army, N=Navy, F=AF)",
    "\\N": "Navigation Buoy",
    "\\O": "Balloon/Rocket (B=Blimp, M=Manned, T=Tethered, C=Constant Pressure, R=Rockoon, W=World-round)",
    "\\P": "Parking",
    "\\Q": "QUAKE",
    "\\R": "Restaurant (7=7/11, K=KFC, M=McDonalds, T=Taco Bell)",
    "\\S": "Satellite/Pacsat",
    "\\T": "Thunderstorm",
    "\\U": "SUNNY",
    "\\V": "VORTAC Nav Aid",
    "\\W": "# NWS site (NWS options)",
    "\\X": "Pharmacy Rx (Apothicary)",
    "\\Y": "Radios/APRS Devices (A=Alinco, B=Byonics, I=Icom, K=Kenwood, Y=Yaesu/Standard)",
    "\\Z": "AVAIL",
    "\\[": "Human/Wall Cloud (B=Baby stroller, S=Skier, R=Runner, H=Hiker)",
    "\\\\": "GPS device (A=Avmap G5)",
    "\\]": "AVAIL",
    "\\^": "Aircraft (A=Autonomous, D=Drone, E=Electric, H=Hovercraft, J=Jet, M=Missile, P=Prop, R=Remotely Piloted, S=Solar, V=VTOL, X=Experimental)",
    "\\_": "# WX site (green digi)",
    "\\`": "Precipitation (R=Rain, F=Freezing Rain, H=Hail, D=Drizzle, E=Sleet, S=Snow)",
    "\\a": "ARRL/ARES/WinLINK (A=ARES, D=DSTAR, G=RSGB, R=RACES, S=SATERN, W=WinLink, Y=C4FM Yaesu)",
    "\\b": "AVAIL(Blwng Dst/Snd => E overlayed)",
    "\\c": "Civil Defense/RACES/SATERN (D=Decontamination, R=RACES, S=SATERN)",
    "\\d": "DX spot by callsign",
    "\\e": "Sleet (& future ovrly codes)",
    "\\f": "Funnel Cloud",
    "\\g": "Gale Flags",
    "\\h": "Store/Hamfest (C=Club, E=Electronics, F=HamFest, H=Hardware)",
    "\\i": "BOX or points of Interest",
    "\\j": "WorkZone (Steam Shovel)",
    "\\k": "Special Vehicle (4=4x4, A=ATV)",
    "\\l": "Areas (box, circles, etc)",
    "\\m": "Value Sign (3 digit display)",
    "\\n": "OVERLAY TRIANGLE",
    "\\o": "small circle",
    "\\p": "AVAIL (Partly Cloudy => ( overlayed P)",
    "\\q": "AVAIL",
    "\\r": "Restrooms",
    "\\s": "Ship/Boat (6=Shipwreck, B=Pleasure, C=Cargo, D=Diving, E=Emergency, F=Fishing, H=High-speed, J=Jet Ski, L=Law, M=Military, O=Oil Rig, P=Pilot, Q=Torpedo, S=SAR, T=Tug, U=Underwater/Sub, W=WIG/Hovercraft, X=Passenger, Y=Sailing)",
    "\\t": "Tornado",
    "\\u": "Truck (B=Bulldozer, G=Gas, P=Plow, T=Tanker, C=Chlorine Tanker, H=Hazardous)",
    "\\v": "OVERLAYED Van",
    "\\w": "Flooding/Water (A=Avalanche, G=Green Gauge, M=Mud slide, N=Normal Gauge, R=Red Gauge, S=Snow Blockage, Y=Yellow Gauge)",
    "\\x": "Wreck or Obstruction ->X<-",
    "\\y": "Skywarn",
    "\\z": "Shelter (C=Clinic, E=Emergency Power, G=Government, M=Morgue, T=Triage)",
    "\\{": "AVAIL? (Fog ==> E overlayed F)",
    "\\|": "TNC Stream Switch",
    "\\}": "AVAIL? (maybe)",
    "\\~": "TNC Stream Switch",
}

def get_symbol_description(table, symbol):
    """Get the description of an APRS symbol."""
    key = f"{table}{symbol}"
    key = key.split('(')[0].strip()
    return APRS_SYMBOLS.get(key, "Unknown Symbol")