# 	Copyright (C) 2026  HafiziRuslan
#
# 	This program is free software: you can redistribute it and/or modify
# 	it under the terms of the GNU General Public License as published by
# 	the Free Software Foundation, either version 3 of the License, or
# 	any later version.
#
# 	This program is distributed in the hope that it will be useful,
# 	but WITHOUT ANY WARRANTY; without even the implied warranty of
# 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# 	GNU General Public License for more details.
#
# 	You should have received a copy of the GNU General Public License
# 	along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
APRS Symbol Definitions
Source: symbolsX.txt (25 Nov 2015), symbols-new.txt (17 Mar 2021)
"""

SYMBOLS = {
	# Primary Symbol Table (/)
	'/!': 'Police, Sheriff',
	'/"': 'reserved',
	'/#': 'DIGI (white center)',
	'/$': 'Phone',
	'/%': 'DX Cluster',
	'/&': 'HF Gateway',
	"/'": 'Small Aircraft',
	'/(': 'Mobile Satellite Station',
	'/)': 'Wheelchair (handicapped)',
	'/*': 'Snow Mobile',
	'/+': 'Red Cross',
	'/,': 'Boy Scouts',
	'/-': 'House QTH (VHF)',
	'/.': 'X',
	'//': 'Red Dot',
	'/0': 'Circle',
	'/1': '',
	'/2': '',
	'/3': '',
	'/4': '',
	'/5': '',
	'/6': '',
	'/7': '',
	'/8': '',
	'/9': '',
	'/:': 'Fire',
	'/;': 'Campground (Portable)',
	'/<': 'Motorcycle',
	'/=': 'Railroad Engine',
	'/>': 'Car',
	'/?': 'Server for Files',
	'/@': 'HC Future predict (dot)',
	'/A': 'Aid Station',
	'/B': 'BBS or PBBS',
	'/C': 'Canoe',
	'/D': '',
	'/E': 'Eyeball (Events, etc!)',
	'/F': 'Farm Vehicle (tractor)',
	'/G': 'Grid Square (6 digit)',
	'/H': 'Hotel (blue bed symbol)',
	'/I': 'TCPIP (on air network station)',
	'/J': '',
	'/K': 'School',
	'/L': 'PC user',
	'/M': 'MacAPRS',
	'/N': 'NTS Station',
	'/O': 'Balloon',
	'/P': 'Police',
	'/Q': '',
	'/R': 'Recovery Vehicle',
	'/S': 'Shuttle',
	'/T': 'SSTV',
	'/U': 'Bus',
	'/V': 'ATV',
	'/W': 'National WX Service Site',
	'/X': 'Helo',
	'/Y': 'Yacht (Sail)',
	'/Z': 'WinAPRS',
	'/[': 'Human/Person',
	'/\\': 'Triangle (DF station)',
	'/]': 'Mail/Post Office',
	'/^': 'Large Aircraft',
	'/_': 'Weather Station (blue)',
	'/`': 'Dish Antenna',
	'/a': 'Ambulance',
	'/b': 'Bike',
	'/c': 'Incident Command Post',
	'/d': 'Fire dept',
	'/e': 'Horse (equestrian)',
	'/f': 'Fire Truck',
	'/g': 'Glider',
	'/h': 'Hospital',
	'/i': 'IOTA (islands on the air)',
	'/j': 'Jeep',
	'/k': 'Truck',
	'/l': 'Laptop',
	'/m': 'Mic-E Repeater',
	'/n': 'Node (black bulls-eye)',
	'/o': 'EOC',
	'/p': 'Rover (puppy, or dog)',
	'/q': 'Grid Square shown above 128 m',
	'/r': 'Repeater',
	'/s': 'Ship (Power Boat)',
	'/t': 'Truck Stop',
	'/u': 'Truck (18 wheeler)',
	'/v': 'Van',
	'/w': 'Water Station',
	'/x': 'xAPRS (Unix)',
	'/y': 'YAGI @ QTH',
	'/z': '',
	'/{': '',
	'/|': 'TNC Stream Switch',
	'/}': '',
	'/~': 'TNC Stream Switch',
	# Secondary/Alternate Symbol Table (\)
	'\\!': 'Emergency',
	'\\"': 'reserved',
	'\\#': 'Digipeater',
	'\\$': 'Bank or ATM',
	'\\%': 'Power Plant',
	'\\&': 'Gateway',
	"\\'": 'Incident',
	'\\(': 'Cloudy',
	'\\)': 'Firenet MEO, MODIS Earth Observation',
	'\\*': '',
	'\\+': 'Church',
	'\\,': 'Girl Scouts',
	'\\-': 'House',
	'\\.': 'Ambiguous (Big Question mark)',
	'\\/': 'Waypoint Destination',
	'\\0': 'Circle',
	'\\1': '',
	'\\2': '',
	'\\3': '',
	'\\4': '',
	'\\5': '',
	'\\6': '',
	'\\7': '',
	'\\8': 'Network Node',
	'\\9': 'Gas Station (blue pump)',
	'\\:': '',
	'\\;': 'Portable/Park/Picnic',
	'\\<': 'ADVISORY (one WX flag)',
	'\\=': 'Rail',
	'\\>': 'Car/Vehicle',
	'\\?': 'INFO Kiosk (Blue box with ?)',
	'\\@': 'HURICANE/Trop-Storm',
	'\\A': 'Box (DTMF/RFID/etc)',
	'\\B': '',
	'\\C': 'Coast Guard',
	'\\D': 'Depot',
	'\\E': 'Visibility',
	'\\F': '',
	'\\G': '',
	'\\H': 'Haze/Hazard',
	'\\I': 'Shower',
	'\\J': '',
	'\\K': 'Kenwood HT (W)',
	'\\L': 'Lighthouse',
	'\\M': 'MARS',
	'\\N': 'Navigation Buoy',
	'\\O': 'Balloon/Rocket',
	'\\P': 'Parking',
	'\\Q': 'Quake',
	'\\R': 'Restaurant',
	'\\S': 'Satellite/Pacsat',
	'\\T': 'Thunderstorm',
	'\\U': 'SUNNY',
	'\\V': 'VORTAC Nav Aid',
	'\\W': 'NWS site (NWS options)',
	'\\X': 'Pharmacy Rx (Apothicary)',
	'\\Y': 'Radios/APRS Devices',
	'\\Z': '',
	'\\[': 'Human/Wall Cloud',
	'\\\\': 'GPS device',
	'\\]': '',
	'\\^': 'Aircraft',
	'\\_': 'WX site (green digi)',
	'\\`': 'Precipitation',
	'\\a': 'ARRL/ARES/WinLINK',
	'\\b': '',
	'\\c': 'Civil Defense/RACES/SATERN',
	'\\d': 'DX spot by callsign',
	'\\e': 'Sleet',
	'\\f': 'Funnel Cloud',
	'\\g': 'Gale Flags',
	'\\h': 'Store/Hamfest',
	'\\i': 'BOX or Points of Interest',
	'\\j': 'WorkZone (Steam Shovel)',
	'\\k': 'Special Vehicle',
	'\\l': 'Areas (box, circles, etc)',
	'\\m': 'Value Sign (3 digit display)',
	'\\n': 'Triangle',
	'\\o': 'Small Circle',
	'\\p': '',
	'\\q': '',
	'\\r': 'Restrooms',
	'\\s': 'Ship/Boat',
	'\\t': 'Tornado',
	'\\u': 'Truck',
	'\\v': 'Van',
	'\\w': 'Flooding/Water',
	'\\x': 'Wreck or Obstruction ->X<-',
	'\\y': 'Skywarn',
	'\\z': 'Shelter',
	'\\{': '',
	'\\|': 'TNC Stream Switch',
	'\\}': '',
	'\\~': 'TNC Stream Switch',
}

OVERLAYS = {
	'#': {
		'1': 'WIDE1-1',
		'A': 'Alt-In',
		'E': 'Emergency',
		'I': 'I-Gate',
		'L': 'trapping',
		'P': 'PacComm',
		'S': 'SSn-N',
		'X': 'eXperimental',
		'V': 'Viscous',
		'W': 'WIDEn-N',
	},
	'$': {'U': 'USD', 'L': 'GBP', 'Y': 'JPY'},
	'%': {
		'C': 'Coal',
		'E': 'Emergency',
		'G': 'Gas',
		'H': 'Hydro',
		'N': 'Nuclear',
		'P': 'Portable',
		'R': 'Renewable',
		'S': 'Solar',
		'T': 'Thermal',
		'W': 'Wind',
	},
	'&': {'2': '2-hop TX', 'I': 'Generic IGate', 'L': 'Lora', 'P': 'PSKmail', 'R': 'RX only', 'T': '1-hop TX', 'W': 'WIRES-X'},
	"'": {'A': 'Auto', 'H': 'Hazardous', 'M': 'Multi-Vehicle', 'P': 'Pileup', 'T': 'Truck wreck'},
	'(': {'P': 'Partly', 'W': 'Wall', 'F': 'Funnel'},
	'-': {
		'5': '50Hz',
		'6': '60Hz',
		'B': 'Battery',
		'C': 'Combined',
		'E': 'Emergency',
		'G': 'Geothermal',
		'H': 'Hydro',
		'O': 'Operator',
		'S': 'Solar',
		'W': 'Wind',
	},
	'0': {'A': 'Allstar', 'E': 'Echolink', 'I': 'IRLP', 'S': 'Staging Area', 'V': 'VOIP', 'W': 'WIRES'},
	'8': {'8': '802.11', 'G': '802.11G'},
	'=': {
		'B': 'Bus-rail',
		'C': 'Commuter',
		'D': 'Diesel',
		'E': 'Electric',
		'F': 'Freight',
		'G': 'Gondola',
		'H': 'High Speed',
		'I': 'Inclined',
		'L': 'Elevated',
		'M': 'Monorail',
		'P': 'Passenger',
		'S': 'Steam',
		'T': 'Terminal',
		'U': 'Subway',
		'X': 'Excursion',
	},
	'>': {
		'1': 'Numbered',
		'2': 'Numbered',
		'3': 'Model 3',
		'4': 'Numbered',
		'5': 'Numbered',
		'6': 'Numbered',
		'7': 'Numbered',
		'8': 'Numbered',
		'9': 'Numbered',
		'B': 'BEV',
		'D': 'DIY',
		'E': 'Ethanol',
		'F': 'Fuelcell',
		'H': 'Hybrid',
		'L': 'Leaf',
		'P': 'PHEV',
		'S': 'Solar',
		'T': 'Tesla',
		'V': 'Volt',
		'X': 'Model X',
	},
	'A': {
		'9': 'Mobile DTMF',
		'7': 'HT DTMF',
		'H': 'House DTMF',
		'E': 'Echolink DTMF',
		'I': 'IRLP DTMF',
		'R': 'RFID',
		'A': 'AllStar DTMF',
		'D': 'D-Star',
		'X': 'OLPC',
	},
	'D': {'A': 'Airport', 'F': 'Ferry', 'H': 'Heloport', 'R': 'Rail', 'B': 'Bus', 'L': 'Light Rail/Subway', 'S': 'Seaport'},
	'E': {'H': 'Haze', 'S': 'Smoke', 'B': 'Blowing Snow', 'D': 'Blowing Dust/Sand', 'F': 'Fog'},
	'H': {'M': 'Methane', 'R': 'Radiation', 'W': 'Hazardous Waste', 'X': 'Skull & Crossbones'},
	'I': {'R': 'Rain', 'S': 'Snow', 'L': 'Lightening'},
	'O': {'B': 'Blimp', 'M': 'Manned', 'T': 'Tethered', 'C': 'Constant Pressure', 'R': 'Rockoon', 'W': 'World-round'},
	'R': {'7': '7/11', 'K': 'KFC', 'M': 'McDonalds', 'T': 'Taco Bell'},
	'[': {'B': 'Baby stroller', 'S': 'Skier', 'R': 'Runner', 'H': 'Hiker'},
	'\\': {'A': 'Avmap G5'},
	'^': {
		'A': 'Autonomous',
		'D': 'Drone',
		'E': 'Electric',
		'H': 'Hovercraft',
		'J': 'Jet',
		'M': 'Missile',
		'P': 'Prop',
		'R': 'Remotely Piloted',
		'S': 'Solar',
		'V': 'VTOL',
		'X': 'Experimental',
	},
	'`': {'R': 'Rain', 'F': 'Freezing Rain', 'H': 'Hail', 'D': 'Drizzle', 'E': 'Sleet', 'S': 'Snow'},
	'a': {'A': 'ARES', 'D': 'DSTAR', 'G': 'RSGB', 'R': 'RACES', 'S': 'SATERN', 'W': 'WinLink', 'Y': 'C4FM Yaesu'},
	'c': {'D': 'Decontamination', 'R': 'RACES', 'S': 'SATERN'},
	's': {
		'6': 'Shipwreck',
		'B': 'Pleasure',
		'C': 'Cargo',
		'D': 'Diving',
		'E': 'Emergency',
		'F': 'Fishing',
		'H': 'High-speed',
		'J': 'Jet Ski',
		'L': 'Law',
		'M': 'Military',
		'O': 'Oil Rig',
		'P': 'Pilot',
		'Q': 'Torpedo',
		'S': 'SAR',
		'T': 'Tug',
		'U': 'Underwater/Submarine',
		'W': 'WIG/Hovercraft',
		'X': 'Passenger',
		'Y': 'Sailing',
	},
	'u': {'B': 'Bulldozer', 'G': 'Gas', 'P': 'Plow', 'T': 'Tanker', 'C': 'Chlorine Tanker', 'H': 'Hazardous'},
	'w': {'A': 'Avalanche', 'G': 'Green Gauge', 'M': 'Mud slide', 'N': 'Normal Gauge', 'R': 'Red Gauge', 'S': 'Snow Blockage', 'Y': 'Yellow Gauge'},
	'z': {'C': 'Clinic', 'E': 'Emergency Power', 'G': 'Government', 'M': 'Morgue', 'T': 'Triage'},
}


def get_desc(table, symbol):
	"""Get the description of an APRS symbol."""
	if table not in ['/', '\\'] and symbol in OVERLAYS:
		base_desc = SYMBOLS.get(f'\\{symbol}', 'Unknown')
		overlay_desc = OVERLAYS[symbol].get(table, f'Overlay {table}')
		return ' '.join(filter(None, [base_desc, overlay_desc]))
	key = f'{table}{symbol}'
	return SYMBOLS.get(key, 'Unknown')
