name: Telegram

on:
  workflow_run:
    workflows:
      - Changelog
    types:
      - completed

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Send Inline Telegram Message
        uses: cbrgm/telegram-github-action@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            New commit on <b><a href="${{ github.event.workflow_run.head_repository.html_url }}/commit/${{ github.event.workflow_run.head_sha }}">${{ github.event.workflow_run.head_repository.full_name }} -> ${{ github.event.workflow_run.head_branch }}</a></b>!
            ———————————
            Ref: <code>${{ steps.vars.outputs.sha_short }}</code> on ${{ github.event.workflow_run.head_commit.timestamp }} by <a href="${{ github.event.sender.html_url }}">@${{ github.event.sender.login }}</a>
            Commit: <pre>${{ github.event.workflow_run.head_commit.message }}</pre>
          parse-mode: 'html'
          disable-web-page-preview: true
          disable-notification: false
          protect-content: true
