name: 'Telegram Message'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Prepare Commit List
        id: vars
        run: |
          {
            echo 'commit_list<<EOF'
            echo "${{ toJson(github.event.commits) }}" | jq -r '.[] | "• \(.message | split("\n")[0]) (<code>\(.id | .[0:7])</code>)"'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Send Inline Telegram Message
        uses: cbrgm/telegram-github-action@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            New push by <b><a href="https://github.com/${{ github.event.sender.login }}">@${{ github.event.sender.login }}</a></b>!
            ----------
            Repository: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            Reference: <code>${{ github.ref_name }}</code>

            <b>Commits:</b>
            ${{ steps.vars.outputs.commit_list }}
          parse-mode: 'html'
          disable-web-page-preview: true
          disable-notification: false
          protect-content: true
